config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'home/index'
  root 'home#index'

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha => true

  def headers
    {
    :subject => "Contact Form",
    :to => "maxsslob@gmail.com",
    :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at DESC")
    @projects = Project.all.limit(3).order("created_at DESC")
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Beautiful, Max! Your article was successfully saved!"
		else
			render 'new', notice: "Oh no, Max! I was unable to save your post!"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Article was successfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all.order("created_at DESC")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.save
      redirect_to @project, notice: "Max! Project has been saved successfully!"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "Updated"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contacts/_sidebar.html.erb
<div class="mobile-nav">
    <header id="mobile-header">
      <div class="mobile-logo">
        <a href="/"><%= image_tag("test.svg", :alt => "logo", class: "logo") %></a>
      </div>
      <h4 class="mobile-title">ABOUT ME</h4>
      <button class="menu-btn" id="menu-btn">
        <span></span><span></span><span></span>
      </button>
    </header>
    <nav id="mobile-menu">
      <ul>
        <li><%= link_to "About", home_index_path %></li>
        <li><%= link_to "Portfolio", projects_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div> <!-- mobile-nav end-->


  <button id="mainMenuOpener">MENU</button>
  <div class="sidebar">
    <div class="logo">
      <a href="/"><%= image_tag("test.svg", :alt => "logo", class: "logo-img") %></a>
      <div id="logo">maxslob.me</div>
    </div>
    <nav>
      <ul id="desktopMenu">
        <li><%= link_to "About", home_index_path %></li>
        <li><%= link_to "Portfolio", projects_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", new_contact_path, class: "selected" %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </nav>
    <div class="social">
      <a href="https://twitter.com/max_slob" target="_blank"><span class="fa fa-twitter"></span></a>
      <a href="https://github.com/maxslob/rails-portfolio-blog" target="_blank"><span class="fa fa-github"></span></a>
      <a href="https://www.linkedin.com/in/maxslob" target="_blank"><span class="fa fa-linkedin"></span></a>
    </div>
  </div> <!-- sidebar end -->

app/views/contacts/create.html.erb
<style type="text/css" media="screen">
  .done #page_title{
    margin-bottom: 3em;
  }
  .done div h1{
    font-size: 2em;
    text-align: center;
  }
  .done div p{
    font-size: 1.5em;
    text-align: center;
  }
  .done{
    margin-bottom: 15em;
  }
</style>
<div class="done">

  <h1 id="page_title">Done!</h1>

  <div class="skinny_wrapper">
    <h1>Thank you for your message!</h1>
    <p>I'll get back to you soon.</p>
  </div>

</div>

app/views/home/_sidebar.html.erb
<div class="mobile-nav">
    <header id="mobile-header">
      <div class="mobile-logo">
        <a href="/"><%= image_tag("test.svg", :alt => "logo", class: "logo") %></a>
      </div>
      <h4 class="mobile-title">ABOUT ME</h4>
      <button class="menu-btn" id="menu-btn">
        <span></span><span></span><span></span>
      </button>
    </header>
    <nav id="mobile-menu">
      <ul>
        <li><%= link_to "About", home_index_path %></li>
        <li><%= link_to "Portfolio", projects_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div> <!-- mobile-nav end-->


  <button id="mainMenuOpener">MENU</button>
  <div class="sidebar">
    <div class="logo">
      <a href="/"><%= image_tag("test.svg", :alt => "logo", class: "logo-img") %></a>
      <div id="logo">maxslob.me</div>
    </div>
    <nav>
      <ul id="desktopMenu">
        <li><%= link_to "About", home_index_path, class: "selected" %></li>
        <li><%= link_to "Portfolio", projects_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </nav>
    <div class="social">
      <a href="https://twitter.com/max_slob" target="_blank"><span class="fa fa-twitter"></span></a>
      <a href="https://github.com/maxslob/rails-portfolio-blog" target="_blank"><span class="fa fa-github"></span></a>
      <a href="https://www.linkedin.com/in/maxslob" target="_blank"><span class="fa fa-linkedin"></span></a>
    </div>
  </div> <!-- sidebar end -->

app/views/home/index.html.erb
    
    <!-- <% @projects.each do |project| %>
      <h3><a href="#"><%= link_to project.title, project %></a></h3>
      <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
    <% end %> -->

  

    <!-- <% @posts.each do |post| %>
      <h3><a href="#"><%= link_to post.title, post %></a></h3>
      <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
    <% end %> -->

<%= stylesheet_link_tag 'app', media: 'all', 'data-turbolinks-track' => true %>
<title>Young Designer & Developer</title>
</head>
<body>
  

  <%= render 'sidebar' %>

  <!-- ABOUT ME MAIN PAGE -->
  <div class="wrapper">
  <div class="hero">
    <img src="http://i.imgur.com/BhqXPXK.jpg" id="me" alt="my-photo">
    <div class="greeting">
      <span>Hello!</span>
      <h2>My name is Max.</h2>
      <h2>I'm Young Developer & Designer</h2>
      <h2>From Minsk, Belarus</h2>
      <%= link_to "Contact Me", new_contact_path %>
    </div>
  </div>
    <h3>ABOUT ME</h3>
    <p class="main-paragraph" id="main-paragraph">
      Last year (2015) I spent learning large bunch of stuff, I've realized that College wont make me a professional or just good at this moreover they want me to go to army, and I must go to the university to avoid it. I'm <b>looking for a job</b> for evenings remote or local, I also <b>want to study, live, work abroad on English language</b>, <b>if you want to help me with english, education, relocation, emigration, I will be very grateful =).</b> What about <b>my knowledge</b>? I do <b>web developing</b>, front-end mostly, I feel myself good at it and I <b>enjoy</b> doing it. Check out my education 
      <span style="position: relative"><span class="tooltip" title="My journey into developing starts from my college where I got the understanding of computer programming. I’ve started from C, then C++ & Java, but at home I learned JS, I've started from html then css, sass, git, design, js, jQuery, Ps & Ai and a lot more technologies, frameworks... I liked that more than desktop programming, because of it's simplicity + I don't need to install IDE's and have a powerfull PC to get started. Then, I’ve been learning basics of Front-End & Design. Now I've solid understanding of how to design & build a website from zero. Everything must be shown on this website. I want to be able to Design and Create a website by myself.">background.</span></span>
       I spend my freetime by learning new, designing, building, travelling, cycling, playing soccer. Enjoy the site! <span id="text">more</span>
    </p>
    <div class="cols">
      <div class="col">
        <h2>SKILLS</h2>
        <button id="modalOpenBtn">OPEN</button>
      </div>
      <div class="col">
        <h2>PORTFOLIO</h2>
        <a href="/projects"><button>OPEN*</button></a>
      </div>
      <div class="col">
        <h2>BLOG</h2>
        <a href="/posts"><button>OPEN*</button></a>
      </div>
    </div>

    <div class="extra-menu">

      <div class="item">
        <span>SKILLS</span>
        <a href="#">OPEN</a>
      </div>

      <div class="item">
        <span>PORTFOLIO</span>
        <a href="#">OPEN</a>
      </div>

      <div class="item">
        <span>BLOG</span>
        <a href="#">OPEN</a>
      </div>

      <div class="item">
        <span>CONTACT</span>
        <a href="#">OPEN</a>
      </div>

    </div> <!-- EXTRA-MENU END -->
    <div class="social">
      <a href="#"><span class="fa fa-twitter"></span></a>
      <a href="#"><span class="fa fa-github"></span></a>
      <a href="#"><span class="fa fa-linkedin"></span></a>
    </div>
  </div> <!-- WRAPPER END -->

  <div class="modal">
    <h2>SKILLS</h2>
    <div class="container">
      <div class="col">
        <h3>FRONT-END</h3>
        <span>HTML, CSS, JS</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
        </ul>

        <span>jQuery</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
        </ul>

        <span>Angular.js</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
          <li id="empty"></li>
        </ul>
      </div>

      <div class="col">
        <h3>DESIGN</h3>
        <span>Web Design</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
        </ul>

        <span>UI, UX</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
          <li id="empty"></li>
        </ul>

        <span>Illustrator</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
          <li id="empty"></li>
        </ul>

        <span>Photoshop</span>
        <ul>
          <li></li>
          <li></li>
          <li id="empty"></li>
          <li id="empty"></li>
          <li id="empty"></li>
        </ul>
      </div>
      <div class="col">
        <h3>OTHER</h3>
        <span>Ruby on Rails</span>
        <ul>
          <li></li>
          <li id="empty"></li>
          <li id="empty"></li>
          <li id="empty"></li>
          <li id="empty"></li>
        </ul>

        <span>SEO</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
        </ul>

        <span>Git</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
        </ul>

        <span>Testing</span>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li id="empty"></li>
        </ul>

        <span>C, C++, Java</span>
        <ul>
          <li></li>
          <li></li>
          <li id="empty"></li>
          <li id="empty"></li>
          <li id="empty"></li>
        </ul>
      </div>
    </div>
    <button id="close"><span class="fa fa-close"></span></button>
  </div>
  

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    var disqus_identifier = '<%= @post.id %>'; 
    var disqus_title = '<%= @post.title %>'; 
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>'; 

    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//maxslob.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, 'error') %> prevented this post from saving: </h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :content, "Write your article here" %> <br>
	<%= f.text_area :content %>

	<br>
	<br>

	<%= f.submit %>
<% end %>

app/views/posts/_sidebar.html.erb
<div class="mobile-nav">
    <header id="mobile-header">
      <div class="mobile-logo">
        <a href="/"><%= image_tag("test.svg", :alt => "logo", class: "logo") %></a>
      </div>
      <h4 class="mobile-title">ABOUT ME</h4>
      <button class="menu-btn" id="menu-btn">
        <span></span><span></span><span></span>
      </button>
    </header>
    <nav id="mobile-menu">
      <ul>
        <li><%= link_to "About", home_index_path %></li>
        <li><%= link_to "Portfolio", projects_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div> <!-- mobile-nav end-->


  <button id="mainMenuOpener">MENU</button>
  <div class="sidebar">
    <div class="logo">
      <a href="/"><%= image_tag("test.svg", :alt => "logo", class: "logo-img") %></a>
      <div id="logo">maxslob.me</div>
    </div>
    <nav>
      <ul id="desktopMenu">
        <li><%= link_to "About", home_index_path %></li>
        <li><%= link_to "Portfolio", projects_path %></li>
        <li><%= link_to "Blog", posts_path, class: "selected" %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </nav>
    <div class="social">
      <a href="https://twitter.com/max_slob" target="_blank"><span class="fa fa-twitter"></span></a>
      <a href="https://github.com/maxslob/rails-portfolio-blog" target="_blank"><span class="fa fa-github"></span></a>
      <a href="https://www.linkedin.com/in/maxslob" target="_blank"><span class="fa fa-linkedin"></span></a>
    </div>
  </div> <!-- sidebar end -->

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'app', media: 'all', 'data-turbolinks-track' => true %>
<title>My Blog</title>
</head>
<body>

  <%= render 'sidebar' %>

  <div class="container">
  <h2>My Blog</h2>

  <div class="item">

    <% @posts.each do |post| %>
    <div class="item-info">
      
      <div class="image blog-image">
        <figure>
          <span class="b-p-title"><%= link_to post.title, post %></span>
          <div class="img">
            <div class="hover"><%= link_to "FULL POST", post %></div>
            <img src="http://i.imgur.com/JXbp83C.jpg" alt="project" />
          </div>
          <figcaption><%= post.created_at.strftime('%b %d, %Y') %></figcaption>
        </figure>
      </div>
      <div class="description" style="position: relative; top: 2.3em;">
        <div class="row">
          <h4>Shorter</h4>
          <p>WILL WORK SOON</p>
        </div>
      </div>
    </div>
    <% end %>

  </div>
  
</div>

app/views/posts/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1 id="page_title">New Post</h1>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'app', media: 'all', 'data-turbolinks-track' => true %>
<title><%= @post.title %></title>
</head>

  <%= render 'sidebar' %>

<div class="image-holder">
  <img src="https://images.unsplash.com/photo-1439546743462-802cabef8e97?fit=crop&fm=jpg&h=1000&ixjsv=2.0.0&ixlib=rb-0.3.5&q=80&w=1925" alt="hero-image" />
  <div class="gradient"></div>
</div>

<div class="container-post">
  <div class="wrapper">
    <h1><%= @post.title %><small><%= @post.created_at.strftime('%b %d, %Y') %></small></h1>
    <hr>
    <article>
       <%= markdown @post.content %>
    </article>
    <% if user_signed_in? %>
      <div id="admin_links">
         <%= link_to "Edit", edit_post_path(@post) %>
        <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete that article?"} %>
      </div>
    <% end %>

    <hr class="hr">

    <div id="share_box">
      <span>Share This Article</span>
      <!-- TWITTER -->
      <a onclick="javascript:window.open('http://twitter.com/share?text= <%= @post.title %> by @max_slob - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300'); void(0);"><i class="fa fa-twitter"></i></a>
    <!-- FACEBOOK -->
      <a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300'); void(0);"><i class="fa fa-facebook"></i></a>
      <!-- GOOGLE PLUS -->
      <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300'); void(0);"><i class="fa fa-google-plus"></i></a>
    </div>

     <hr class="share-box-hr">

      <%= render 'disqus' %>
  </div>
</div>


<!-- <div id="post_show_content" class="skinny_wrapper">
    <div class="title">
      <h2><%= @post.title %></h2>
      <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
      <hr>
    </div>

    <div id="content">
      <%= markdown @post.content %>
    </div>


  
  
</div> post-show-content-end

 -->

app/views/projects/_sidebar.html.erb
<div class="mobile-nav">
    <header id="mobile-header">
      <div class="mobile-logo">
        <a href="/"><%= image_tag("test.svg", :alt => "logo", class: "logo") %></a>
      </div>
      <h4 class="mobile-title">ABOUT ME</h4>
      <button class="menu-btn" id="menu-btn">
        <span></span><span></span><span></span>
      </button>
    </header>
    <nav id="mobile-menu">
      <ul>
        <li><%= link_to "About", home_index_path %></li>
        <li><%= link_to "Portfolio", projects_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div> <!-- mobile-nav end-->


  <button id="mainMenuOpener">MENU</button>
  <div class="sidebar">
    <div class="logo">
      <a href="/"><%= image_tag("test.svg", :alt => "logo", class: "logo-img") %></a>
      <div id="logo">maxslob.me</div>
    </div>
    <nav>
      <ul id="desktopMenu">
        <li><%= link_to "About", home_index_path %></li>
        <li><%= link_to "Portfolio", projects_path, class: "selected" %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </nav>
    <div class="social">
      <a href="https://twitter.com/max_slob" target="_blank"><span class="fa fa-twitter"></span></a>
      <a href="https://github.com/maxslob/rails-portfolio-blog" target="_blank"><span class="fa fa-github"></span></a>
      <a href="https://www.linkedin.com/in/maxslob" target="_blank"><span class="fa fa-linkedin"></span></a>
    </div>
  </div> <!-- sidebar end -->

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>

<div class="skinny_wrapper wrapper_padding">
  
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<%= stylesheet_link_tag 'app', media: 'all', 'data-turbolinks-track' => true %>
<title>My Portfolio</title>
</head>

<body>

  <%= render 'sidebar' %>

  <div class="container">
  <h2>Projects</h2>

  <div class="item">
  
  <% @projects.each do |project| %>
  <div class="item-info">
      
      <div class="image proj-image">
        <figure>
          <span class="b-p-title"><%= link_to project.title, project %></span>
          <div class="img">
            <div class="hover"><%= link_to "OPEN", project.link, target: "_blank" %></div>
            <img src="http://i.imgur.com/SekwlLal.png" alt="project" />
          </div>
          <figcaption><%= project.created_at.strftime('%b %d, %Y') %></figcaption>
        </figure>
      </div>
      <div class="description" style="position: relative; top: 2.3em;">
        <div class="row">
          <h4>Description</h4>
          <p>This functionality will be available soon.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore numquam, atque ipsam. Quisquam commodi odit consequatur debitis, quas facere omnis!</p>
        </div>
        <div class="row">
          <h4>Skills</h4>
          <p>This functionality will be available soon.</p>
        </div>
        <% if user_signed_in? %>
          <div id="admin_links">
            <%= link_to "Edit Project", edit_project_path(project) %>
            <%= link_to "Delete Project", project_path(project), method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>

  </div>
  
</div>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper">
   <div class="title"> 
      <h2><%= @project.title %></h2>
      <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
      <hr id="hr-darkred">
  </div>

    <div id="content">
      <div id="description">
        <%= markdown @project.description %>
      </div>
      <div class="button_wrapper">
        <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
      </div>   
    </div>

    <hr id="hr-red">
    <% if user_signed_in? %>
    <div id="admin_links">
      <%= link_to "Edit Project", edit_project_path(@project) %>
      <%= link_to "Delete Project", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>

  <%= render 'disqus' %>
  
</div>